# fly.toml app configuration file generated for quiet-water-7642 on 2023-06-29T21:52:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-water-7642"
primary_region = "sea"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
